version: '2.1'

volumes:
  pihole_config:
  dnsmasq_config:

services:
  pihole:
    build: ./pihole
    privileged: true
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    cap_add:
      - 'NET_ADMIN'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    network_mode: host

  unbound:
    image: klutchell/unbound:1.9.0-arm
    ports:
      - '1053:53/tcp'
      - '1053:53/udp'

  dohnut:
    image: klutchell/dohnut:v4.1.1-arm
    ports:
      - '5053:53/tcp'
      - '5053:53/udp'
    command: --listen 0.0.0.0:53 --doh cleanbrowsing cloudflare quad9 mozilla
