version: '2.1'

volumes:

  pihole_config:
  dnsmasq_config:
  duplicati_config:
  ssh_config:
  cloud9_workspace:
  cloud9_home:

services:

  # https://github.com/pi-hole/docker-pi-hole/
  # https://hub.docker.com/r/pihole/pihole/
  pihole:
    image: pihole/pihole:v4.0_armhf
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    entrypoint: ['/bin/bash', '-c', 'echo "bind-interfaces" >> /etc/dnsmasq.conf; /s6-init']
    network_mode: host

  # https://github.com/visibilityspots/dockerfile-cloudflared
  # https://hub.docker.com/r/visibilityspots/cloudflared/
  cloudflared:
    image: visibilityspots/cloudflared:arm
    ports:
      - '54:54/tcp'
      - '54:54/udp'

  # https://github.com/linuxserver/docker-duplicati-armhf
  # https://hub.docker.com/r/lsioarmhf/duplicati/
  duplicati:
    image: lsioarmhf/duplicati
    ports:
      - '8200:8200/tcp'
    volumes:
      - 'pihole_config:/source/pihole_config:ro'
      - 'dnsmasq_config:/source/dnsmasq_config:ro'
      - 'cloud9_workspace:/source/cloud9_workspace:ro'
      - 'cloud9_home:/source/cloud9_home:ro'
      - 'duplicati_config:/config'
  
  # https://github.com/klutchell/docker-ssh
  # https://hub.docker.com/r/klutchell/ssh/
  ssh:
    image: klutchell/ssh:armhf
    ports:
      - '22:22/tcp'
    volumes:
      - 'ssh_config:/root/.ssh'

  cloud9:
    image: klutchell/cloud9:armhf
    ports:
      - '8080:8080'
    volumes:
      - 'cloud9_workspace:/workspace'
      - 'cloud9_home:/root'
    privileged: true
    network_mode: host
