version: '2.1'

volumes:

  pihole_config:
  dnsmasq_config:

services:

  # https://hub.docker.com/r/pihole/pihole/
  pihole:
    image: pihole/pihole:4.1.1_armhf
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    entrypoint:
      - '/bin/bash'
      - '-c'
      - 'grep -q "bind-interfaces" /etc/dnsmasq.conf || echo "bind-interfaces" >> /etc/dnsmasq.conf; /s6-init'
    cap_add:
      - 'NET_ADMIN'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    network_mode: host

  # https://hub.docker.com/r/klutchell/unbound/
  unbound:
    image: klutchell/unbound:armv7hf-2.0.1
    ports:
      - '1053:53/tcp'
      - '1053:53/udp'
