version: '2.1'

volumes:

  pi-hole-data:
  dnsmasq-data:
  duplicati-data:

services:

  # https://github.com/pi-hole/docker-pi-hole/
  # https://hub.docker.com/r/pihole/pihole/
  pi-hole:
    image: pihole/pihole:v4.0_armhf
    ports:
      - '80:80'
      - '192.168.86.22:443:443/tcp'
      - '192.168.86.22:53/tcp'
      - '192.168.86.22:53/udp'
    volumes:
      - 'pi-hole-data:/etc/pihole'
      - 'dnsmasq-data:/etc/dnsmasq.d'

  cloudflared:
    image: visibilityspots/cloudflared:arm
    ports:
      - '54:54'

  duplicati:
    image: lsioarmhf/duplicati
    ports:
      - '8200:8200'
    volumes:
      - 'pi-hole-data:/source/pi-hole-data:ro'
      - 'dnsmasq-data:/source/dnsmasq-data:ro'
      - 'duplicati-data:/config'
