version: "2.1"

volumes:
  pihole_config:
  dnsmasq_config:

services:
  # https://hub.docker.com/r/pihole/pihole
  pihole:
    build: ./pihole
    privileged: true
    volumes:
      - "pihole_config:/etc/pihole"
      - "dnsmasq_config:/etc/dnsmasq.d"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    environment:
      DNSMASQ_LISTENING: eth0
      INTERFACE: eth0
      DNS1: 127.0.0.1#5335
      DNS2: 127.0.0.1#5335
    network_mode: host
    labels:
      io.balena.features.dbus: "1"

  # https://hub.docker.com/r/klutchell/unbound-dnscrypt
  unbound:
    build: ./unbound
    privileged: true
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
