version: '2.1'

volumes:

  pi-hole-data:
  dnsmasq-data:

services:

  pi-hole:
    image: diginc/pi-hole-multiarch:debian_armhf
    ports:
      - '80:80'
      - '192.168.86.12:53:53/tcp'
      - '192.168.86.12:53:53/udp'
    volumes:
      - 'pi-hole-data:/etc/pihole'
      - 'dnsmasq-data:/etc/dnsmasq.d'

  cloudflared:
    image: visibilityspots/cloudflared:arm
    ports:
      - '54:54'

  duplicati:
    image: lsioarmhf/duplicati
    ports:
      - '8200:8200'
    volumes:
      - 'pi-hole-data:/source/pi-hole-data:ro'
      - 'dnsmasq-data:/source/dnsmasq-data:ro'
