version: "2.1"

volumes:
  pihole_config:
  dnsmasq_config:

services:
  # https://hub.docker.com/r/pihole/pihole
  pihole:
    build: ./pihole
    privileged: true
    volumes:
      - "pihole_config:/etc/pihole"
      - "dnsmasq_config:/etc/dnsmasq.d"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    network_mode: host

  # https://github.com/klutchell/unbound-dnscrypt
  unbound:
    build: ./unbound
    privileged: true
    ports:
      - "5053:5053/tcp"
      - "5053:5053/udp"
    networks:
      - my_ipv6_bridge

  # https://github.com/balenablocks/fbcp
  fbcp:
    image: balenablocks/fbcp:1.0.0
    privileged: true

  # prevent plymouth from blocking fbcp
  # https://github.com/klutchell/balena-pihole/issues/25
  # https://github.com/balena-os/meta-balena/issues/1772
  dbus:
    build: dbus
    restart: on-failure
    labels:
        io.balena.features.dbus: "1"

networks:
  my_ipv6_bridge:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1
