version: '2.1'

volumes:

  pihole_config:
  dnsmasq_config:

services:

  pihole:
    build: ./pihole
    privileged: true
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    entrypoint:
      - '/bin/bash'
      - '-c'
      - 'grep -q "bind-interfaces" /etc/dnsmasq.conf || echo "bind-interfaces" >> /etc/dnsmasq.conf; /s6-init'
    cap_add:
      - 'NET_ADMIN'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    network_mode: host

  unbound:
    build: ./unbound
    ports:
      - '1053:53/tcp'
      - '1053:53/udp'
